### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by EuanChan** [tripleCC/cocoapods-tdfire-binary#19]
执行 pod binary init，报错，内容如下：

```
➜ pod binary init

开始设置二进制化初始信息.
所有的信息都会保存在 binary_config.yaml 文件中.
你可以在 /Users/euanc/.cocoapods/binary_config.yml 目录下手动添加编辑该文件.
/Users/euanc/.cocoapods/binary_config.yml 文件包含配置信息如下：

---
server_host: 输入二进制服务器地址 (比如 http://xxxxx:8080)
repo_url: 输入私有源 Git 地址 (比如 https://github.com/tripleCC/PrivateSpecRepo.git)
template_url: 输入 pod 模版 Git 地址 (比如 https://github.com/CocoaPods/pod-template.git)
```

### Command

```
/Users/euanc/.rvm/gems/ruby-2.3.1/bin/pod binary init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
    RubyGems : 2.7.2
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.3 (9E145)
         Git : git version 2.16.3
Ruby lib dir : /Users/euanc/.rvm/rubies/ruby-2.3.1/lib
Repositories : artsy - https://github.com/Artsy/Specs.git @ 024234e2b9a2f48bf4f0e5104512b45a353af2d8
               master - https://github.com/CocoaPods/Specs.git @ fcd57ba35ab25f6af5258fff459463acf6bd8813
               meitu-git - http://techgit.meitu.com/iosmodules/specs.git @ 304468a33f40e3c7796d666e0e08fb2ef47b5412
               meitu-imeipai-specs - http://techgit.meitu.com/imeipai/Specs.git @ b4b4f614cb363e17831d864f06d2415700fde3f5
               meitu-imeitupic-specs - http://techgit.meitu.com/iMeituPic/specs.git @ 6a108c035b250303499e9273106cce17b99c7402
               meitu-iosmodules_public-specs - http://techgit.meitu.com/iosmodules_public/specs.git @ f2fd983ccf358f28f4cefb9e7e8bfcecd20a09d0
               meitu-specs - git@techgit.meitu.com:iosmodules/specs.git @ 304468a33f40e3c7796d666e0e08fb2ef47b5412
```

### Plugins

```
cocoapods-binary        : 0.3.6
cocoapods-deintegrate   : 1.0.2
cocoapods-packager      : 1.5.0
cocoapods-plugins       : 1.0.0
cocoapods-search        : 1.0.0
cocoapods-stats         : 1.0.0
cocoapods-tdfire-binary : 1.2.1
cocoapods-trunk         : 1.3.0
cocoapods-try           : 1.1.0
```

### Error

```
NoMethodError - undefined method `[]' for nil:NilClass
/Users/euanc/.rvm/gems/ruby-2.3.1/gems/cocoapods-tdfire-binary-1.2.1/lib/cocoapods-tdfire-binary/command/init.rb:26:in `block in run'
/Users/euanc/.rvm/gems/ruby-2.3.1/gems/cocoapods-tdfire-binary-1.2.1/lib/cocoapods-tdfire-binary/command/init.rb:25:in `each'
/Users/euanc/.rvm/gems/ruby-2.3.1/gems/cocoapods-tdfire-binary-1.2.1/lib/cocoapods-tdfire-binary/command/init.rb:25:in `run'
/Users/euanc/.rvm/gems/ruby-2.3.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/euanc/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Users/euanc/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/Users/euanc/.rvm/gems/ruby-2.3.1/bin/pod:23:in `load'
/Users/euanc/.rvm/gems/ruby-2.3.1/bin/pod:23:in `<main>'
/Users/euanc/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/euanc/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tripleCC** [comment]
@EuanChan  master 上修复了
